name = 'simple'
license = 'MIT'
licenselink = 'https://github.com/gabr1sr/simple-hugo-theme'
description = 'Minimal, readable and comfortable Hugo theme using a modern font and without any tracking or external dependencies.'
homepage = 'https://github.com/gabr1sr/simple-hugo-theme'
tags = ['blog', 'minimal', 'no-js', 'no-tracking']
features = ['blog', 'fast', 'comfortable']
min_version = '0.20'

[author]
  name = 'morph'
  homepage = 'morph.sh'

[original]
  author = 'morph'
  homepage = 'morph.sh'
  repo = 'https://github.com/colorchestra/smol'
